### ISSUE TITLE
Issues while getAccountInformation()

### ISSUE THREAD

**Issue by bd901029** [tinymanorg/tinyman-js-sdk#63]
I'm adding sdk to my backend and getAccountInformation() returns followings:

{
  address: '44JWBWM3YFHZWSY...',
  amount: 44999000,
  'amount-without-pending-rewards': 44999000,
  'apps-local-state': [],
  'apps-total-schema': { 'num-byte-slice': 0, 'num-uint': 0 },
  assets: [ { amount: 300000000, 'asset-id': 10458941, 'is-frozen': false } ],
  'created-apps': [],
  'created-assets': [],
  'min-balance': 200000,
  'pending-rewards': 0,
  'reward-base': 27521,
  rewards: 0,
  round: 24688863,
  status: 'Offline',
  'total-apps-opted-in': 0,
  'total-assets-opted-in': 1,
  'total-created-apps': 0,
  'total-created-assets': 0,
  minimum_required_balance: 200000
}

"status" is 'Offline' and it seems a reason. and then isAccountOptedIntoApp() returns error:

TypeError: Cannot read properties of undefined (reading 'some')
    at exports.isAccountOptedIntoApp (/Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@tinymanorg/tinyman-js-sdk/dist/index.js:3:55595)
    at TinyMan.optIn (/Volumes/WORK/AutoBookie/autobookie-backend/src/algo/tinyman.js:31:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at AlgoService.convertAlgoToUsdc (/Volumes/WORK/AutoBookie/autobookie-backend/src/algo/algo.service.ts:76:3)
    at UsersService.withdraw (/Volumes/WORK/AutoBookie/autobookie-backend/src/users/users.service.ts:164:4)
    at UsersController.withdraw (/Volumes/WORK/AutoBookie/autobookie-backend/src/users/users.controller.ts:51:4)
    at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /Volumes/WORK/AutoBookie/autobookie-backend/node_modules/@nestjs/core/router/router-proxy.js:9:17

Anybody faced same issue?

**Comment by edizcelik** [comment]
This error would be thrown if the second argument provided to `isAccountOptedIntoApp ` is `undefined`. Once you get the account information, you should provide `apps-local-state` as the second argument to `isAccountOptedIntoApp`:

```
const account = await getAccountInformation(algodClient, accountAddress);
const hasOptedIn = isAccountOptedIntoApp(validatorAppID, account["apps-local-state"]);
```

**Comment by bd901029** [comment]
@edizcelik As I attached the response of getAccountInformation(), account["apps-local-state"] is empty array. I have some module to get local state. Plz lemme know what information are required to pass as local state.

**Comment by bd901029** [comment]
@edizcelik I'm getting local state through your function: getAccountInformation(), based on the readme. but it returns empty array...

**Comment by jamcry** [comment]
Hi @bd901029 , you can probably understand the issue by basic debugging by `console.log`ging the values

```tsx
const account = await getAccountInformation(algodClient, accountAddress);
const appsLocalState = account["apps-local-state"];

console.log({account, appsLocalState});

console.log({
  // `isAccountOptedIntoApp` expects the arguments in an object:
  hasOptedIn: isAccountOptedIntoApp({
    appID: validatorAppID,
    accountAppsLocalState: appsLocalState
  })
});
```

I guess the problem is that you are passing arguments directly to the function (`fn(a,b)`), but this function actually expects them in object (`fn({a,b})`). You can see from the source code [here](https://github.com/tinymanorg/tinyman-js-sdk/blob/main/src/util/account/accountUtils.ts). Also if you're using VSCode, it should be showing you the expected argument type.

If `appsLocalState` is an array (even if it's empty), then `isAccountOptedIntoApp` shouldn't raise an error.
